export const SHOW_POSTS = 'POST/SHOW_POSTS'

export const SHOW_POSTS_SUCCESS = 'POST/SHOW_POSTS_SUCCESS';

export const SHOW_AUTHORS = 'AUTHOR/SHOW_AUTHORS';

export const SHOW_AUTHORS_SUCCESS = 'AUTHOR/SHOW_AUTHORS_SUCCESS';
